// default package
// Generated Mar 25, 2017 6:47:10 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuthorArticleMappingId generated by hbm2java
 */
@Embeddable
public class AuthorArticleMappingId implements java.io.Serializable {

	private String name;
	private String articleKey;
	private int authorId;

	public AuthorArticleMappingId() {
	}

	public AuthorArticleMappingId(int authorId) {
		this.authorId = authorId;
	}

	public AuthorArticleMappingId(String name, String articleKey, int authorId) {
		this.name = name;
		this.articleKey = articleKey;
		this.authorId = authorId;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "article_key", length = 200)
	public String getArticleKey() {
		return this.articleKey;
	}

	public void setArticleKey(String articleKey) {
		this.articleKey = articleKey;
	}

	@Column(name = "Author_Id", nullable = false)
	public int getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(int authorId) {
		this.authorId = authorId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuthorArticleMappingId))
			return false;
		AuthorArticleMappingId castOther = (AuthorArticleMappingId) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
				&& this.getName().equals(castOther.getName())))
				&& ((this.getArticleKey() == castOther.getArticleKey()) || (this.getArticleKey() != null
						&& castOther.getArticleKey() != null && this.getArticleKey().equals(castOther.getArticleKey())))
				&& (this.getAuthorId() == castOther.getAuthorId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getArticleKey() == null ? 0 : this.getArticleKey().hashCode());
		result = 37 * result + this.getAuthorId();
		return result;
	}

}
