// default package
// Generated Mar 25, 2017 6:47:10 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AuthorPaperMapping generated by hbm2java
 */
@Entity
@Table(name = "author_paper_mapping", catalog = "dblp")
public class AuthorPaperMapping implements java.io.Serializable {

	private AuthorPaperMappingId id;

	public AuthorPaperMapping() {
	}

	public AuthorPaperMapping(AuthorPaperMappingId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "name", column = @Column(name = "name", length = 100) ),
			@AttributeOverride(name = "paperKey", column = @Column(name = "paper_key", length = 200) ),
			@AttributeOverride(name = "authorId", column = @Column(name = "Author_Id", nullable = false) ),
			@AttributeOverride(name = "paperId", column = @Column(name = "Paper_Id", nullable = false) ) })
	public AuthorPaperMappingId getId() {
		return this.id;
	}

	public void setId(AuthorPaperMappingId id) {
		this.id = id;
	}

}
