// default package
// Generated Mar 25, 2017 6:47:10 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuthorPaperMappingId generated by hbm2java
 */
@Embeddable
public class AuthorPaperMappingId implements java.io.Serializable {

	private String name;
	private String paperKey;
	private int authorId;
	private int paperId;

	public AuthorPaperMappingId() {
	}

	public AuthorPaperMappingId(int authorId, int paperId) {
		this.authorId = authorId;
		this.paperId = paperId;
	}

	public AuthorPaperMappingId(String name, String paperKey, int authorId, int paperId) {
		this.name = name;
		this.paperKey = paperKey;
		this.authorId = authorId;
		this.paperId = paperId;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "paper_key", length = 200)
	public String getPaperKey() {
		return this.paperKey;
	}

	public void setPaperKey(String paperKey) {
		this.paperKey = paperKey;
	}

	@Column(name = "Author_Id", nullable = false)
	public int getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(int authorId) {
		this.authorId = authorId;
	}

	@Column(name = "Paper_Id", nullable = false)
	public int getPaperId() {
		return this.paperId;
	}

	public void setPaperId(int paperId) {
		this.paperId = paperId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuthorPaperMappingId))
			return false;
		AuthorPaperMappingId castOther = (AuthorPaperMappingId) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
				&& this.getName().equals(castOther.getName())))
				&& ((this.getPaperKey() == castOther.getPaperKey()) || (this.getPaperKey() != null
						&& castOther.getPaperKey() != null && this.getPaperKey().equals(castOther.getPaperKey())))
				&& (this.getAuthorId() == castOther.getAuthorId()) && (this.getPaperId() == castOther.getPaperId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getPaperKey() == null ? 0 : this.getPaperKey().hashCode());
		result = 37 * result + this.getAuthorId();
		result = 37 * result + this.getPaperId();
		return result;
	}

}
