// default package
// Generated Mar 25, 2017 6:47:10 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Committee generated by hbm2java
 */
@Entity
@Table(name = "committee", catalog = "dblp")
public class Committee implements java.io.Serializable {

	private Integer id;
	private String confName;
	private Integer year;
	private String editor;
	private String position;
	private int conferenceId;

	public Committee() {
	}

	public Committee(int conferenceId) {
		this.conferenceId = conferenceId;
	}

	public Committee(String confName, Integer year, String editor, String position, int conferenceId) {
		this.confName = confName;
		this.year = year;
		this.editor = editor;
		this.position = position;
		this.conferenceId = conferenceId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "conf_name", length = 200)
	public String getConfName() {
		return this.confName;
	}

	public void setConfName(String confName) {
		this.confName = confName;
	}

	@Column(name = "year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "editor", length = 100)
	public String getEditor() {
		return this.editor;
	}

	public void setEditor(String editor) {
		this.editor = editor;
	}

	@Column(name = "position", length = 10)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "conference_id", nullable = false)
	public int getConferenceId() {
		return this.conferenceId;
	}

	public void setConferenceId(int conferenceId) {
		this.conferenceId = conferenceId;
	}

}
