// default package
// Generated Mar 25, 2017 6:47:10 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ConferenceEditorMapping generated by hbm2java
 */
@Entity
@Table(name = "conference_editor_mapping", catalog = "dblp")
public class ConferenceEditorMapping implements java.io.Serializable {

	private Integer id;
	private int confId;
	private int editorId;

	public ConferenceEditorMapping() {
	}

	public ConferenceEditorMapping(int confId, int editorId) {
		this.confId = confId;
		this.editorId = editorId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "confId", nullable = false)
	public int getConfId() {
		return this.confId;
	}

	public void setConfId(int confId) {
		this.confId = confId;
	}

	@Column(name = "editorId", nullable = false)
	public int getEditorId() {
		return this.editorId;
	}

	public void setEditorId(int editorId) {
		this.editorId = editorId;
	}

}
