// default package
// Generated Mar 25, 2017 6:47:10 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Paper generated by hbm2java
 */
@Entity
@Table(name = "paper", catalog = "dblp")
public class Paper implements java.io.Serializable {

	private Integer paperId;
	private String paperKey;
	private String title;
	private String bookTitle;
	private Integer year;
	private String conference;
	private String url;
	private String conferenceName;

	public Paper() {
	}

	public Paper(String paperKey, String title, String bookTitle, Integer year, String conference, String url,
			String conferenceName) {
		this.paperKey = paperKey;
		this.title = title;
		this.bookTitle = bookTitle;
		this.year = year;
		this.conference = conference;
		this.url = url;
		this.conferenceName = conferenceName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "paper_id", unique = true, nullable = false)
	public Integer getPaperId() {
		return this.paperId;
	}

	public void setPaperId(Integer paperId) {
		this.paperId = paperId;
	}

	@Column(name = "paper_key", length = 200)
	public String getPaperKey() {
		return this.paperKey;
	}

	public void setPaperKey(String paperKey) {
		this.paperKey = paperKey;
	}

	@Column(name = "title", length = 65535)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "book_title", length = 65535)
	public String getBookTitle() {
		return this.bookTitle;
	}

	public void setBookTitle(String bookTitle) {
		this.bookTitle = bookTitle;
	}

	@Column(name = "year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "conference", length = 65535)
	public String getConference() {
		return this.conference;
	}

	public void setConference(String conference) {
		this.conference = conference;
	}

	@Column(name = "url", length = 65535)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "conference_name", length = 200)
	public String getConferenceName() {
		return this.conferenceName;
	}

	public void setConferenceName(String conferenceName) {
		this.conferenceName = conferenceName;
	}

}
