// default package
// Generated Mar 25, 2017 6:47:10 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Proceeding generated by hbm2java
 */
@Entity
@Table(name = "proceeding", catalog = "dblp")
public class Proceeding implements java.io.Serializable {

	private Integer proceedingId;
	private String proceedingKey;
	private String title;
	private String bookTitle;
	private String isbn;
	private Integer year;
	private String url;

	public Proceeding() {
	}

	public Proceeding(String proceedingKey, String title, String bookTitle, String isbn, Integer year, String url) {
		this.proceedingKey = proceedingKey;
		this.title = title;
		this.bookTitle = bookTitle;
		this.isbn = isbn;
		this.year = year;
		this.url = url;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "proceeding_id", unique = true, nullable = false)
	public Integer getProceedingId() {
		return this.proceedingId;
	}

	public void setProceedingId(Integer proceedingId) {
		this.proceedingId = proceedingId;
	}

	@Column(name = "proceeding_key", length = 200)
	public String getProceedingKey() {
		return this.proceedingKey;
	}

	public void setProceedingKey(String proceedingKey) {
		this.proceedingKey = proceedingKey;
	}

	@Column(name = "title", length = 65535)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "book_title", length = 65535)
	public String getBookTitle() {
		return this.bookTitle;
	}

	public void setBookTitle(String bookTitle) {
		this.bookTitle = bookTitle;
	}

	@Column(name = "isbn", length = 65535)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "year")
	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	@Column(name = "url", length = 65535)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
